### ISSUE TITLE
Possible data races without locking

### ISSUE THREAD

**Issue by ycaibb** [openpmix/pmix-tests#127]
Hi, it seems the lock_handle should be protected by locks?

https://github.com/openpmix/pmix-tests/blob/765fa58a6d2794bdef2509f00827879f6f02e1a7/prrte/debug/test-utils.c#L33

https://github.com/openpmix/pmix-tests/blob/765fa58a6d2794bdef2509f00827879f6f02e1a7/prrte/debug/test-utils.c#L79-L91

Just like this.
```
 void lock_stream() { 
     pthread_mutex_lock(&thread_lock); 
     if (0 < lock_handle) { 
         flock(lock_handle, LOCK_EX); 
     } 
 } 
  
 void unlock_stream() { 
     if (0 < lock_handle) { 
         flock(lock_handle, LOCK_UN); 
     } 
     pthread_mutex_unlock(&thread_lock); 
 } 
```

**Comment by rhc54** [comment]
@jjhursey This is your folks test - what do you think? It seems reasonable to me.

**Comment by jjhursey** [comment]
I think that patch is good. @dwootton-ny Can you take a look and submit up a patch if it looks good to you as well?

**Comment by drwootton** [comment]
I think that part of the change is ok. Additionally, I think I need to move the lock_stream() call before the call to printf_common() in each of the printf wrappers since that it what actually sets lock_handle.

I think I can have a pull request for this later this afternoon after I code and run a couple tests.

**Comment by jjhursey** [comment]
The fix was just merged as PR https://github.com/openpmix/pmix-tests/pull/130 with the changes to `printf_common` mentioned above. Thanks for the bug report!
